apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: wso2das-fluentd
  namespace: appcloud-extensions
  labels:
    k8s-app: fluentd-logging
spec:
  template:
    metadata:
      labels:
        name: fluentd-logging
    spec:
      containers:
      - name: wso2das-fluentd
        image: registry.cloudstaging.wso2.com:5000/wso2das-fluentd:1.0.0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

