apiVersion: v1
kind: Service
metadata:
  annotations:
    serviceloadbalancer/lb.host: "wso2.influxdb.com"
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-heapster
spec:
  type: NodePort
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    nodePort: 32083
  - name: api
    port: 8086
    targetPort: 8086
    nodePort: 32086
  selector:
    name: influxdb
