apiVersion: v1
kind: ReplicationController
metadata:
  name: service-loadbalancer-private
  labels:
    app: service-loadbalancer-private
    version: v1
spec:
  replicas: 2
  selector:
    app: service-loadbalancer-private
    version: v1
  template:
    metadata:
      labels:
        app: service-loadbalancer-private
        version: v1
    spec:
      #nodeSelector:
       # role: loadbalancer
      containers:
      - image: registry.182.docker.appfactory.private.wso2.com:5000/haproxy-dev:0.4-0.7.2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: haproxy
        ports:
        # All http services
        - containerPort: 80
          hostPort: 10080
          protocol: TCP
        # nginx https
        - containerPort: 443
          hostPort: 18443
          protocol: TCP
        # mysql
        - containerPort: 3306
          hostPort: 13306
          protocol: TCP
        # haproxy stats
        - containerPort: 1936
          hostPort: 11936
          protocol: TCP
        resources: {}
        args:
        - --tcp-services=mysql:3306,nginxsvc:443
        - --ssl-cert= /etc/haproxy/ssl.pem
        - --ssl-ca-cert=/etc/haproxy/ca.crt
        - --syslog=true
        - --load-balancer-type=private

